<?php
/**
 * GENERATED by tools/extract.ts — do not edit. Run `bun tools/extract.ts`.
 *
 * Every palette and every typeface the blog engine offers, already turned into CSS by the
 * blog engine's own emitters. `quireink_appearance_css()` in inc/customizer.php picks the
 * one the owner chose and prints it after the stylesheets, exactly where Quire Ink inlines
 * its own settings block.
 *
 * @package QuireInk
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Palette id => first-paint scheme => the :root and .dark declarations.
 *
 * @return array<string,array<string,string>>
 */
function quireink_palette_css() {
	return array(
	'mono' => array(
		'system' => ':root{color-scheme:light;--c-bg:#fcfcfc;--c-text:#262626;--c-heading:#121212;--c-meta:#6d6d6d;--c-link:#121212;--c-accent:#121212;--c-rule:#ebebeb}.dark{color-scheme:dark;--c-bg:#0e0e0e;--c-text:#d6d6d6;--c-heading:#f2f2f2;--c-meta:#888888;--c-link:#f2f2f2;--c-accent:#f2f2f2;--c-rule:#262626}@media (prefers-color-scheme:dark){:root:not([data-scheme]){color-scheme:dark;--c-bg:#0e0e0e;--c-text:#d6d6d6;--c-heading:#f2f2f2;--c-meta:#888888;--c-link:#f2f2f2;--c-accent:#f2f2f2;--c-rule:#262626}}',
		'light' => ':root{color-scheme:light;--c-bg:#fcfcfc;--c-text:#262626;--c-heading:#121212;--c-meta:#6d6d6d;--c-link:#121212;--c-accent:#121212;--c-rule:#ebebeb}.dark{color-scheme:dark;--c-bg:#0e0e0e;--c-text:#d6d6d6;--c-heading:#f2f2f2;--c-meta:#888888;--c-link:#f2f2f2;--c-accent:#f2f2f2;--c-rule:#262626}',
		'dark' => ':root{color-scheme:light;--c-bg:#fcfcfc;--c-text:#262626;--c-heading:#121212;--c-meta:#6d6d6d;--c-link:#121212;--c-accent:#121212;--c-rule:#ebebeb}.dark{color-scheme:dark;--c-bg:#0e0e0e;--c-text:#d6d6d6;--c-heading:#f2f2f2;--c-meta:#888888;--c-link:#f2f2f2;--c-accent:#f2f2f2;--c-rule:#262626}:root:not([data-scheme]){color-scheme:dark;--c-bg:#0e0e0e;--c-text:#d6d6d6;--c-heading:#f2f2f2;--c-meta:#888888;--c-link:#f2f2f2;--c-accent:#f2f2f2;--c-rule:#262626}',
	),
	'sepia' => array(
		'system' => ':root{color-scheme:light;--c-bg:#f6f1e7;--c-text:#44372a;--c-heading:#2c2218;--c-meta:#706657;--c-link:#955832;--c-accent:#955832;--c-rule:#e3d8c4}.dark{color-scheme:dark;--c-bg:#211b14;--c-text:#ddd0bd;--c-heading:#f2e9d8;--c-meta:#9c8e79;--c-link:#d79b6c;--c-accent:#d79b6c;--c-rule:#3a3025}@media (prefers-color-scheme:dark){:root:not([data-scheme]){color-scheme:dark;--c-bg:#211b14;--c-text:#ddd0bd;--c-heading:#f2e9d8;--c-meta:#9c8e79;--c-link:#d79b6c;--c-accent:#d79b6c;--c-rule:#3a3025}}',
		'light' => ':root{color-scheme:light;--c-bg:#f6f1e7;--c-text:#44372a;--c-heading:#2c2218;--c-meta:#706657;--c-link:#955832;--c-accent:#955832;--c-rule:#e3d8c4}.dark{color-scheme:dark;--c-bg:#211b14;--c-text:#ddd0bd;--c-heading:#f2e9d8;--c-meta:#9c8e79;--c-link:#d79b6c;--c-accent:#d79b6c;--c-rule:#3a3025}',
		'dark' => ':root{color-scheme:light;--c-bg:#f6f1e7;--c-text:#44372a;--c-heading:#2c2218;--c-meta:#706657;--c-link:#955832;--c-accent:#955832;--c-rule:#e3d8c4}.dark{color-scheme:dark;--c-bg:#211b14;--c-text:#ddd0bd;--c-heading:#f2e9d8;--c-meta:#9c8e79;--c-link:#d79b6c;--c-accent:#d79b6c;--c-rule:#3a3025}:root:not([data-scheme]){color-scheme:dark;--c-bg:#211b14;--c-text:#ddd0bd;--c-heading:#f2e9d8;--c-meta:#9c8e79;--c-link:#d79b6c;--c-accent:#d79b6c;--c-rule:#3a3025}',
	),
	'forest' => array(
		'system' => ':root{color-scheme:light;--c-bg:#f5f7f2;--c-text:#2c352c;--c-heading:#1c241c;--c-meta:#646c60;--c-link:#3b764a;--c-accent:#3b764a;--c-rule:#dde5d8}.dark{color-scheme:dark;--c-bg:#0f140f;--c-text:#cdd6c8;--c-heading:#e9efe5;--c-meta:#7e8a78;--c-link:#79b389;--c-accent:#79b389;--c-rule:#252e23}@media (prefers-color-scheme:dark){:root:not([data-scheme]){color-scheme:dark;--c-bg:#0f140f;--c-text:#cdd6c8;--c-heading:#e9efe5;--c-meta:#7e8a78;--c-link:#79b389;--c-accent:#79b389;--c-rule:#252e23}}',
		'light' => ':root{color-scheme:light;--c-bg:#f5f7f2;--c-text:#2c352c;--c-heading:#1c241c;--c-meta:#646c60;--c-link:#3b764a;--c-accent:#3b764a;--c-rule:#dde5d8}.dark{color-scheme:dark;--c-bg:#0f140f;--c-text:#cdd6c8;--c-heading:#e9efe5;--c-meta:#7e8a78;--c-link:#79b389;--c-accent:#79b389;--c-rule:#252e23}',
		'dark' => ':root{color-scheme:light;--c-bg:#f5f7f2;--c-text:#2c352c;--c-heading:#1c241c;--c-meta:#646c60;--c-link:#3b764a;--c-accent:#3b764a;--c-rule:#dde5d8}.dark{color-scheme:dark;--c-bg:#0f140f;--c-text:#cdd6c8;--c-heading:#e9efe5;--c-meta:#7e8a78;--c-link:#79b389;--c-accent:#79b389;--c-rule:#252e23}:root:not([data-scheme]){color-scheme:dark;--c-bg:#0f140f;--c-text:#cdd6c8;--c-heading:#e9efe5;--c-meta:#7e8a78;--c-link:#79b389;--c-accent:#79b389;--c-rule:#252e23}',
	),
	'ocean' => array(
		'system' => ':root{color-scheme:light;--c-bg:#f4f7fa;--c-text:#28323d;--c-heading:#16202b;--c-meta:#616b74;--c-link:#2b6cae;--c-accent:#2b6cae;--c-rule:#dbe4ec}.dark{color-scheme:dark;--c-bg:#0c121a;--c-text:#c7d2dd;--c-heading:#e8eef5;--c-meta:#7c8a98;--c-link:#6aa9e0;--c-accent:#6aa9e0;--c-rule:#202a36}@media (prefers-color-scheme:dark){:root:not([data-scheme]){color-scheme:dark;--c-bg:#0c121a;--c-text:#c7d2dd;--c-heading:#e8eef5;--c-meta:#7c8a98;--c-link:#6aa9e0;--c-accent:#6aa9e0;--c-rule:#202a36}}',
		'light' => ':root{color-scheme:light;--c-bg:#f4f7fa;--c-text:#28323d;--c-heading:#16202b;--c-meta:#616b74;--c-link:#2b6cae;--c-accent:#2b6cae;--c-rule:#dbe4ec}.dark{color-scheme:dark;--c-bg:#0c121a;--c-text:#c7d2dd;--c-heading:#e8eef5;--c-meta:#7c8a98;--c-link:#6aa9e0;--c-accent:#6aa9e0;--c-rule:#202a36}',
		'dark' => ':root{color-scheme:light;--c-bg:#f4f7fa;--c-text:#28323d;--c-heading:#16202b;--c-meta:#616b74;--c-link:#2b6cae;--c-accent:#2b6cae;--c-rule:#dbe4ec}.dark{color-scheme:dark;--c-bg:#0c121a;--c-text:#c7d2dd;--c-heading:#e8eef5;--c-meta:#7c8a98;--c-link:#6aa9e0;--c-accent:#6aa9e0;--c-rule:#202a36}:root:not([data-scheme]){color-scheme:dark;--c-bg:#0c121a;--c-text:#c7d2dd;--c-heading:#e8eef5;--c-meta:#7c8a98;--c-link:#6aa9e0;--c-accent:#6aa9e0;--c-rule:#202a36}',
	),
	'scifi' => array(
		'system' => ':root{color-scheme:light;--c-bg:#f2f5f7;--c-text:#1e2a33;--c-heading:#0d161e;--c-meta:#5f6a75;--c-link:#0b7284;--c-accent:#0b7284;--c-rule:#dce4ea}.dark{color-scheme:dark;--c-bg:#0a0f15;--c-text:#c3d2dc;--c-heading:#e7f1f7;--c-meta:#778591;--c-link:#36cfe0;--c-accent:#36cfe0;--c-rule:#1b2630}@media (prefers-color-scheme:dark){:root:not([data-scheme]){color-scheme:dark;--c-bg:#0a0f15;--c-text:#c3d2dc;--c-heading:#e7f1f7;--c-meta:#778591;--c-link:#36cfe0;--c-accent:#36cfe0;--c-rule:#1b2630}}',
		'light' => ':root{color-scheme:light;--c-bg:#f2f5f7;--c-text:#1e2a33;--c-heading:#0d161e;--c-meta:#5f6a75;--c-link:#0b7284;--c-accent:#0b7284;--c-rule:#dce4ea}.dark{color-scheme:dark;--c-bg:#0a0f15;--c-text:#c3d2dc;--c-heading:#e7f1f7;--c-meta:#778591;--c-link:#36cfe0;--c-accent:#36cfe0;--c-rule:#1b2630}',
		'dark' => ':root{color-scheme:light;--c-bg:#f2f5f7;--c-text:#1e2a33;--c-heading:#0d161e;--c-meta:#5f6a75;--c-link:#0b7284;--c-accent:#0b7284;--c-rule:#dce4ea}.dark{color-scheme:dark;--c-bg:#0a0f15;--c-text:#c3d2dc;--c-heading:#e7f1f7;--c-meta:#778591;--c-link:#36cfe0;--c-accent:#36cfe0;--c-rule:#1b2630}:root:not([data-scheme]){color-scheme:dark;--c-bg:#0a0f15;--c-text:#c3d2dc;--c-heading:#e7f1f7;--c-meta:#778591;--c-link:#36cfe0;--c-accent:#36cfe0;--c-rule:#1b2630}',
	),
	'amber' => array(
		'system' => ':root{color-scheme:light;--c-bg:#fcfbf8;--c-text:#2e2a26;--c-heading:#1a1714;--c-meta:#716c66;--c-link:#9f5c09;--c-accent:#9f5c09;--c-rule:#ece7df}.dark{color-scheme:dark;--c-bg:#100f0d;--c-text:#d6d2ca;--c-heading:#f3f0ea;--c-meta:#8a857c;--c-link:#e8a13c;--c-accent:#e8a13c;--c-rule:#272420}@media (prefers-color-scheme:dark){:root:not([data-scheme]){color-scheme:dark;--c-bg:#100f0d;--c-text:#d6d2ca;--c-heading:#f3f0ea;--c-meta:#8a857c;--c-link:#e8a13c;--c-accent:#e8a13c;--c-rule:#272420}}',
		'light' => ':root{color-scheme:light;--c-bg:#fcfbf8;--c-text:#2e2a26;--c-heading:#1a1714;--c-meta:#716c66;--c-link:#9f5c09;--c-accent:#9f5c09;--c-rule:#ece7df}.dark{color-scheme:dark;--c-bg:#100f0d;--c-text:#d6d2ca;--c-heading:#f3f0ea;--c-meta:#8a857c;--c-link:#e8a13c;--c-accent:#e8a13c;--c-rule:#272420}',
		'dark' => ':root{color-scheme:light;--c-bg:#fcfbf8;--c-text:#2e2a26;--c-heading:#1a1714;--c-meta:#716c66;--c-link:#9f5c09;--c-accent:#9f5c09;--c-rule:#ece7df}.dark{color-scheme:dark;--c-bg:#100f0d;--c-text:#d6d2ca;--c-heading:#f3f0ea;--c-meta:#8a857c;--c-link:#e8a13c;--c-accent:#e8a13c;--c-rule:#272420}:root:not([data-scheme]){color-scheme:dark;--c-bg:#100f0d;--c-text:#d6d2ca;--c-heading:#f3f0ea;--c-meta:#8a857c;--c-link:#e8a13c;--c-accent:#e8a13c;--c-rule:#272420}',
	),
	);
}

/**
 * Reading typeface id => the family, the type scale tuned for it, and its CJK tail.
 *
 * @return array<string,string>
 */
function quireink_font_css() {
	return array(
	'inter' => ':root{--font-reading:\'Inter\', \'Inter Fallback\', \'Inter Fallback 2\', system-ui, -apple-system, \'Segoe UI\', \'PingFang SC\', \'Microsoft YaHei\', \'Noto Sans CJK SC\', \'Noto Sans SC\', \'Hiragino Sans\', \'Yu Gothic\', \'Noto Sans CJK JP\', \'Noto Sans JP\', \'Apple SD Gothic Neo\', \'Malgun Gothic\', \'Noto Sans CJK KR\', \'Noto Sans KR\', sans-serif}:lang(zh){--font-reading:\'Inter\', \'Inter Fallback\', \'Inter Fallback 2\', system-ui, -apple-system, \'Segoe UI\', \'PingFang SC\', \'Microsoft YaHei\', \'Noto Sans CJK SC\', \'Noto Sans SC\', sans-serif}:lang(ja){--font-reading:\'Inter\', \'Inter Fallback\', \'Inter Fallback 2\', system-ui, -apple-system, \'Segoe UI\', \'Hiragino Sans\', \'Yu Gothic\', \'Noto Sans CJK JP\', \'Noto Sans JP\', sans-serif}:lang(ko){--font-reading:\'Inter\', \'Inter Fallback\', \'Inter Fallback 2\', system-ui, -apple-system, \'Segoe UI\', \'Apple SD Gothic Neo\', \'Malgun Gothic\', \'Noto Sans CJK KR\', \'Noto Sans KR\', sans-serif}',
	'source-sans' => ':root{--font-reading:\'Source Sans 3\', \'Source Sans 3 Fallback\', \'Source Sans 3 Fallback 2\', system-ui, -apple-system, \'PingFang SC\', \'Microsoft YaHei\', \'Noto Sans CJK SC\', \'Noto Sans SC\', \'Hiragino Sans\', \'Yu Gothic\', \'Noto Sans CJK JP\', \'Noto Sans JP\', \'Apple SD Gothic Neo\', \'Malgun Gothic\', \'Noto Sans CJK KR\', \'Noto Sans KR\', sans-serif}:lang(zh){--font-reading:\'Source Sans 3\', \'Source Sans 3 Fallback\', \'Source Sans 3 Fallback 2\', system-ui, -apple-system, \'PingFang SC\', \'Microsoft YaHei\', \'Noto Sans CJK SC\', \'Noto Sans SC\', sans-serif}:lang(ja){--font-reading:\'Source Sans 3\', \'Source Sans 3 Fallback\', \'Source Sans 3 Fallback 2\', system-ui, -apple-system, \'Hiragino Sans\', \'Yu Gothic\', \'Noto Sans CJK JP\', \'Noto Sans JP\', sans-serif}:lang(ko){--font-reading:\'Source Sans 3\', \'Source Sans 3 Fallback\', \'Source Sans 3 Fallback 2\', system-ui, -apple-system, \'Apple SD Gothic Neo\', \'Malgun Gothic\', \'Noto Sans CJK KR\', \'Noto Sans KR\', sans-serif}',
	'literata' => ':root{--font-reading:\'Literata\', \'Literata Fallback\', \'Literata Fallback 2\', Georgia, \'Times New Roman\', \'Songti SC\', \'SimSun\', \'Noto Serif CJK SC\', \'Noto Serif SC\', \'Hiragino Mincho ProN\', \'Yu Mincho\', \'Noto Serif CJK JP\', \'Noto Serif JP\', \'Nanum Myeongjo\', \'Apple SD Gothic Neo\', \'Noto Serif CJK KR\', \'Noto Serif KR\', serif;--reading-bold:600}:lang(zh){--font-reading:\'Literata\', \'Literata Fallback\', \'Literata Fallback 2\', Georgia, \'Times New Roman\', \'Songti SC\', \'SimSun\', \'Noto Serif CJK SC\', \'Noto Serif SC\', serif}:lang(ja){--font-reading:\'Literata\', \'Literata Fallback\', \'Literata Fallback 2\', Georgia, \'Times New Roman\', \'Hiragino Mincho ProN\', \'Yu Mincho\', \'Noto Serif CJK JP\', \'Noto Serif JP\', serif}:lang(ko){--font-reading:\'Literata\', \'Literata Fallback\', \'Literata Fallback 2\', Georgia, \'Times New Roman\', \'Nanum Myeongjo\', \'Apple SD Gothic Neo\', \'Noto Serif CJK KR\', \'Noto Serif KR\', serif}',
	'source-serif' => ':root{--font-reading:\'Source Serif 4\', \'Source Serif 4 Fallback\', \'Source Serif 4 Fallback 2\', Georgia, \'Times New Roman\', \'Songti SC\', \'SimSun\', \'Noto Serif CJK SC\', \'Noto Serif SC\', \'Hiragino Mincho ProN\', \'Yu Mincho\', \'Noto Serif CJK JP\', \'Noto Serif JP\', \'Nanum Myeongjo\', \'Apple SD Gothic Neo\', \'Noto Serif CJK KR\', \'Noto Serif KR\', serif;--reading-bold:600}:lang(zh){--font-reading:\'Source Serif 4\', \'Source Serif 4 Fallback\', \'Source Serif 4 Fallback 2\', Georgia, \'Times New Roman\', \'Songti SC\', \'SimSun\', \'Noto Serif CJK SC\', \'Noto Serif SC\', serif}:lang(ja){--font-reading:\'Source Serif 4\', \'Source Serif 4 Fallback\', \'Source Serif 4 Fallback 2\', Georgia, \'Times New Roman\', \'Hiragino Mincho ProN\', \'Yu Mincho\', \'Noto Serif CJK JP\', \'Noto Serif JP\', serif}:lang(ko){--font-reading:\'Source Serif 4\', \'Source Serif 4 Fallback\', \'Source Serif 4 Fallback 2\', Georgia, \'Times New Roman\', \'Nanum Myeongjo\', \'Apple SD Gothic Neo\', \'Noto Serif CJK KR\', \'Noto Serif KR\', serif}',
	);
}

/**
 * Chrome typeface id => the family for the furniture.
 *
 * @return array<string,string>
 */
function quireink_chrome_css() {
	return array(
	'inter' => '',
	'reading' => ':root{--font-sans:var(--font-reading)}',
	'plex-mono' => ':root{--font-sans:\'IBM Plex Mono\', ui-monospace, \'SFMono-Regular\', Menlo, Consolas, monospace}',
	'jetbrains-mono' => ':root{--font-sans:\'JetBrains Mono\', ui-monospace, \'SFMono-Regular\', Menlo, Consolas, monospace}',
	);
}

/**
 * Frame id => the four `--fig-default-*` variables `figure img` reads when a picture names
 * no frame of its own. `none` is absent because it emits nothing.
 *
 * @return array<string,string>
 */
function quireink_figure_css() {
	return array(
	'thin' => ':root{--fig-default-pad:var(--fig-step-thin);--fig-default-mat:var(--c-bg);--fig-default-bw:1px;--fig-default-line:var(--c-rule);--fig-default-line:color-mix(in srgb,var(--c-rule),var(--c-meta) 35%)}',
	'thin-ink' => ':root{--fig-default-pad:var(--fig-step-thin);--fig-default-mat:var(--c-heading);--fig-default-bw:1px;--fig-default-line:var(--c-rule);--fig-default-line:var(--c-heading)}',
	'medium' => ':root{--fig-default-pad:var(--fig-step-med);--fig-default-mat:var(--c-bg);--fig-default-bw:1px;--fig-default-line:var(--c-rule);--fig-default-line:color-mix(in srgb,var(--c-rule),var(--c-meta) 35%)}',
	'medium-ink' => ':root{--fig-default-pad:var(--fig-step-med);--fig-default-mat:var(--c-heading);--fig-default-bw:1px;--fig-default-line:var(--c-rule);--fig-default-line:var(--c-heading)}',
	'thick' => ':root{--fig-default-pad:var(--fig-step-thick);--fig-default-mat:var(--c-bg);--fig-default-bw:1px;--fig-default-line:var(--c-rule);--fig-default-line:color-mix(in srgb,var(--c-rule),var(--c-meta) 35%)}',
	'thick-ink' => ':root{--fig-default-pad:var(--fig-step-thick);--fig-default-mat:var(--c-heading);--fig-default-bw:1px;--fig-default-line:var(--c-rule);--fig-default-line:var(--c-heading)}',
	);
}
