<?php
/**
 * GENERATED by tools/extract.ts — do not edit. Run `bun tools/extract.ts`.
 *
 * Every palette and every typeface the blog engine offers, already turned into CSS by the
 * blog engine's own emitters. `quireink_appearance_css()` in inc/customizer.php picks the
 * one the owner chose and prints it after the stylesheets, exactly where Quire Ink inlines
 * its own settings block.
 *
 * @package QuireInk
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * The blog engine's drop cap, addressed at the class the block editor writes.
 *
 * Gutenberg offers a drop cap on any paragraph and styles it 8.4em at weight 100, which is
 * three times this theme's own and a weight its typefaces do not carry. These are the
 * engine's declarations, taken from its book-mode sheet at build time.
 *
 * @return string
 */
function quireink_dropcap_css() {
	return '.prose .has-drop-cap:not(:focus)::first-letter{float:left;margin:.02em .09em 0 0; font-size:3.1em;line-height:.72;font-weight:600;color:var(--c-heading)}';
}

/**
 * What the generated sheet already carries, as the blog engine set it at extract time.
 *
 * `quireink_appearance_css()` prints a setting's declarations only when the setting differs
 * from one of these. They are the ENGINE's defaults, not the theme's: the theme's furniture
 * face is JetBrains Mono and the engine's is Inter, and comparing against the wrong one left
 * `--font-sans` at the engine's value on every default install.
 *
 * @return array<string,string>
 */
function quireink_engine_defaults() {
	return array(
		'palette' => 'mono',
		'font' => 'literata',
		'chrome' => 'inter',
	);
}

/**
 * Palette id => first-paint scheme => the :root and .dark declarations.
 *
 * @return array<string,array<string,string>>
 */
function quireink_palette_css() {
	return array(
	'mono' => array(
		'system' => ':root{color-scheme:light;--c-bg:#fcfcfc;--c-text:#30302f;--c-heading:#1a1919;--c-meta:#6d6c6c;--c-link:#1a1919;--c-accent:#1a1919;--c-rule:#e3e2e2}.dark{color-scheme:dark;--c-bg:#0e0e0e;--c-text:#d4d4d3;--c-heading:#f1f0f0;--c-meta:#868685;--c-link:#f1f0f0;--c-accent:#f1f0f0;--c-rule:#2a2a29}@media (prefers-color-scheme:dark){:root:not([data-scheme]){color-scheme:dark;--c-bg:#0e0e0e;--c-text:#d4d4d3;--c-heading:#f1f0f0;--c-meta:#868685;--c-link:#f1f0f0;--c-accent:#f1f0f0;--c-rule:#2a2a29}}',
		'light' => ':root{color-scheme:light;--c-bg:#fcfcfc;--c-text:#30302f;--c-heading:#1a1919;--c-meta:#6d6c6c;--c-link:#1a1919;--c-accent:#1a1919;--c-rule:#e3e2e2}.dark{color-scheme:dark;--c-bg:#0e0e0e;--c-text:#d4d4d3;--c-heading:#f1f0f0;--c-meta:#868685;--c-link:#f1f0f0;--c-accent:#f1f0f0;--c-rule:#2a2a29}',
		'dark' => ':root{color-scheme:light;--c-bg:#fcfcfc;--c-text:#30302f;--c-heading:#1a1919;--c-meta:#6d6c6c;--c-link:#1a1919;--c-accent:#1a1919;--c-rule:#e3e2e2}.dark{color-scheme:dark;--c-bg:#0e0e0e;--c-text:#d4d4d3;--c-heading:#f1f0f0;--c-meta:#868685;--c-link:#f1f0f0;--c-accent:#f1f0f0;--c-rule:#2a2a29}:root:not([data-scheme]){color-scheme:dark;--c-bg:#0e0e0e;--c-text:#d4d4d3;--c-heading:#f1f0f0;--c-meta:#868685;--c-link:#f1f0f0;--c-accent:#f1f0f0;--c-rule:#2a2a29}',
	),
	'sepia' => array(
		'system' => ':root{color-scheme:light;--c-bg:#fcf7ed;--c-text:#372a1e;--c-heading:#1d140a;--c-meta:#736959;--c-link:#91552e;--c-accent:#91552e;--c-rule:#e8ddc8}.dark{color-scheme:dark;--c-bg:#1a140e;--c-text:#e5d8c4;--c-heading:#fff6e4;--c-meta:#968974;--c-link:#db9f6f;--c-accent:#db9f6f;--c-rule:#362d22}@media (prefers-color-scheme:dark){:root:not([data-scheme]){color-scheme:dark;--c-bg:#1a140e;--c-text:#e5d8c4;--c-heading:#fff6e4;--c-meta:#968974;--c-link:#db9f6f;--c-accent:#db9f6f;--c-rule:#362d22}}',
		'light' => ':root{color-scheme:light;--c-bg:#fcf7ed;--c-text:#372a1e;--c-heading:#1d140a;--c-meta:#736959;--c-link:#91552e;--c-accent:#91552e;--c-rule:#e8ddc8}.dark{color-scheme:dark;--c-bg:#1a140e;--c-text:#e5d8c4;--c-heading:#fff6e4;--c-meta:#968974;--c-link:#db9f6f;--c-accent:#db9f6f;--c-rule:#362d22}',
		'dark' => ':root{color-scheme:light;--c-bg:#fcf7ed;--c-text:#372a1e;--c-heading:#1d140a;--c-meta:#736959;--c-link:#91552e;--c-accent:#91552e;--c-rule:#e8ddc8}.dark{color-scheme:dark;--c-bg:#1a140e;--c-text:#e5d8c4;--c-heading:#fff6e4;--c-meta:#968974;--c-link:#db9f6f;--c-accent:#db9f6f;--c-rule:#362d22}:root:not([data-scheme]){color-scheme:dark;--c-bg:#1a140e;--c-text:#e5d8c4;--c-heading:#fff6e4;--c-meta:#968974;--c-link:#db9f6f;--c-accent:#db9f6f;--c-rule:#362d22}',
	),
	'forest' => array(
		'system' => ':root{color-scheme:light;--c-bg:#f5f7f2;--c-text:#262e26;--c-heading:#0f170f;--c-meta:#646b60;--c-link:#336f43;--c-accent:#336f43;--c-rule:#d8dfd3}.dark{color-scheme:dark;--c-bg:#0f140f;--c-text:#d1dacc;--c-heading:#f0f7ec;--c-meta:#808d7a;--c-link:#7db78c;--c-accent:#7db78c;--c-rule:#262f23}@media (prefers-color-scheme:dark){:root:not([data-scheme]){color-scheme:dark;--c-bg:#0f140f;--c-text:#d1dacc;--c-heading:#f0f7ec;--c-meta:#808d7a;--c-link:#7db78c;--c-accent:#7db78c;--c-rule:#262f23}}',
		'light' => ':root{color-scheme:light;--c-bg:#f5f7f2;--c-text:#262e26;--c-heading:#0f170f;--c-meta:#646b60;--c-link:#336f43;--c-accent:#336f43;--c-rule:#d8dfd3}.dark{color-scheme:dark;--c-bg:#0f140f;--c-text:#d1dacc;--c-heading:#f0f7ec;--c-meta:#808d7a;--c-link:#7db78c;--c-accent:#7db78c;--c-rule:#262f23}',
		'dark' => ':root{color-scheme:light;--c-bg:#f5f7f2;--c-text:#262e26;--c-heading:#0f170f;--c-meta:#646b60;--c-link:#336f43;--c-accent:#336f43;--c-rule:#d8dfd3}.dark{color-scheme:dark;--c-bg:#0f140f;--c-text:#d1dacc;--c-heading:#f0f7ec;--c-meta:#808d7a;--c-link:#7db78c;--c-accent:#7db78c;--c-rule:#262f23}:root:not([data-scheme]){color-scheme:dark;--c-bg:#0f140f;--c-text:#d1dacc;--c-heading:#f0f7ec;--c-meta:#808d7a;--c-link:#7db78c;--c-accent:#7db78c;--c-rule:#262f23}',
	),
	'ocean' => array(
		'system' => ':root{color-scheme:light;--c-bg:#f0f8ff;--c-text:#212d3b;--c-heading:#091623;--c-meta:#616b73;--c-link:#2466a7;--c-accent:#2466a7;--c-rule:#d1dfed}.dark{color-scheme:dark;--c-bg:#031127;--c-text:#cad8e6;--c-heading:#edf4fd;--c-meta:#7c8a97;--c-link:#6fafe6;--c-accent:#6fafe6;--c-rule:#1b2d42}@media (prefers-color-scheme:dark){:root:not([data-scheme]){color-scheme:dark;--c-bg:#031127;--c-text:#cad8e6;--c-heading:#edf4fd;--c-meta:#7c8a97;--c-link:#6fafe6;--c-accent:#6fafe6;--c-rule:#1b2d42}}',
		'light' => ':root{color-scheme:light;--c-bg:#f0f8ff;--c-text:#212d3b;--c-heading:#091623;--c-meta:#616b73;--c-link:#2466a7;--c-accent:#2466a7;--c-rule:#d1dfed}.dark{color-scheme:dark;--c-bg:#031127;--c-text:#cad8e6;--c-heading:#edf4fd;--c-meta:#7c8a97;--c-link:#6fafe6;--c-accent:#6fafe6;--c-rule:#1b2d42}',
		'dark' => ':root{color-scheme:light;--c-bg:#f0f8ff;--c-text:#212d3b;--c-heading:#091623;--c-meta:#616b73;--c-link:#2466a7;--c-accent:#2466a7;--c-rule:#d1dfed}.dark{color-scheme:dark;--c-bg:#031127;--c-text:#cad8e6;--c-heading:#edf4fd;--c-meta:#7c8a97;--c-link:#6fafe6;--c-accent:#6fafe6;--c-rule:#1b2d42}:root:not([data-scheme]){color-scheme:dark;--c-bg:#031127;--c-text:#cad8e6;--c-heading:#edf4fd;--c-meta:#7c8a97;--c-link:#6fafe6;--c-accent:#6fafe6;--c-rule:#1b2d42}',
	),
	'scifi' => array(
		'system' => ':root{color-scheme:light;--c-bg:#f6f8f7;--c-text:#292d31;--c-heading:#141619;--c-meta:#666a70;--c-link:#006f75;--c-accent:#006f75;--c-rule:#dcdfe1}.dark{color-scheme:dark;--c-bg:#0d0f11;--c-text:#d1d5d8;--c-heading:#eef2f3;--c-meta:#81888d;--c-link:#00b9c4;--c-accent:#00b9c4;--c-rule:#262a2f}@media (prefers-color-scheme:dark){:root:not([data-scheme]){color-scheme:dark;--c-bg:#0d0f11;--c-text:#d1d5d8;--c-heading:#eef2f3;--c-meta:#81888d;--c-link:#00b9c4;--c-accent:#00b9c4;--c-rule:#262a2f}}',
		'light' => ':root{color-scheme:light;--c-bg:#f6f8f7;--c-text:#292d31;--c-heading:#141619;--c-meta:#666a70;--c-link:#006f75;--c-accent:#006f75;--c-rule:#dcdfe1}.dark{color-scheme:dark;--c-bg:#0d0f11;--c-text:#d1d5d8;--c-heading:#eef2f3;--c-meta:#81888d;--c-link:#00b9c4;--c-accent:#00b9c4;--c-rule:#262a2f}',
		'dark' => ':root{color-scheme:light;--c-bg:#f6f8f7;--c-text:#292d31;--c-heading:#141619;--c-meta:#666a70;--c-link:#006f75;--c-accent:#006f75;--c-rule:#dcdfe1}.dark{color-scheme:dark;--c-bg:#0d0f11;--c-text:#d1d5d8;--c-heading:#eef2f3;--c-meta:#81888d;--c-link:#00b9c4;--c-accent:#00b9c4;--c-rule:#262a2f}:root:not([data-scheme]){color-scheme:dark;--c-bg:#0d0f11;--c-text:#d1d5d8;--c-heading:#eef2f3;--c-meta:#81888d;--c-link:#00b9c4;--c-accent:#00b9c4;--c-rule:#262a2f}',
	),
	'amber' => array(
		'system' => ':root{color-scheme:light;--c-bg:#fcfbf8;--c-text:#322e2a;--c-heading:#1c1915;--c-meta:#6f6b65;--c-link:#975500;--c-accent:#975500;--c-rule:#e5e1d9}.dark{color-scheme:dark;--c-bg:#100f0d;--c-text:#d9d5cc;--c-heading:#f5f1eb;--c-meta:#8b867d;--c-link:#e09932;--c-accent:#e09932;--c-rule:#2d2a25}@media (prefers-color-scheme:dark){:root:not([data-scheme]){color-scheme:dark;--c-bg:#100f0d;--c-text:#d9d5cc;--c-heading:#f5f1eb;--c-meta:#8b867d;--c-link:#e09932;--c-accent:#e09932;--c-rule:#2d2a25}}',
		'light' => ':root{color-scheme:light;--c-bg:#fcfbf8;--c-text:#322e2a;--c-heading:#1c1915;--c-meta:#6f6b65;--c-link:#975500;--c-accent:#975500;--c-rule:#e5e1d9}.dark{color-scheme:dark;--c-bg:#100f0d;--c-text:#d9d5cc;--c-heading:#f5f1eb;--c-meta:#8b867d;--c-link:#e09932;--c-accent:#e09932;--c-rule:#2d2a25}',
		'dark' => ':root{color-scheme:light;--c-bg:#fcfbf8;--c-text:#322e2a;--c-heading:#1c1915;--c-meta:#6f6b65;--c-link:#975500;--c-accent:#975500;--c-rule:#e5e1d9}.dark{color-scheme:dark;--c-bg:#100f0d;--c-text:#d9d5cc;--c-heading:#f5f1eb;--c-meta:#8b867d;--c-link:#e09932;--c-accent:#e09932;--c-rule:#2d2a25}:root:not([data-scheme]){color-scheme:dark;--c-bg:#100f0d;--c-text:#d9d5cc;--c-heading:#f5f1eb;--c-meta:#8b867d;--c-link:#e09932;--c-accent:#e09932;--c-rule:#2d2a25}',
	),
	);
}

/**
 * Reading typeface id => the family, the type scale tuned for it, and its CJK tail.
 *
 * @return array<string,string>
 */
function quireink_font_css() {
	return array(
	'inter' => ':root{--font-reading:\'Inter\', \'Inter Fallback\', \'Inter Fallback 2\', system-ui, -apple-system, \'Segoe UI\', \'PingFang SC\', \'Microsoft YaHei\', \'Noto Sans CJK SC\', \'Noto Sans SC\', \'Hiragino Sans\', \'Yu Gothic\', \'Noto Sans CJK JP\', \'Noto Sans JP\', \'Apple SD Gothic Neo\', \'Malgun Gothic\', \'Noto Sans CJK KR\', \'Noto Sans KR\', sans-serif}:lang(zh){--font-reading:\'Inter\', \'Inter Fallback\', \'Inter Fallback 2\', system-ui, -apple-system, \'Segoe UI\', \'PingFang SC\', \'Microsoft YaHei\', \'Noto Sans CJK SC\', \'Noto Sans SC\', sans-serif}:lang(ja){--font-reading:\'Inter\', \'Inter Fallback\', \'Inter Fallback 2\', system-ui, -apple-system, \'Segoe UI\', \'Hiragino Sans\', \'Yu Gothic\', \'Noto Sans CJK JP\', \'Noto Sans JP\', sans-serif}:lang(ko){--font-reading:\'Inter\', \'Inter Fallback\', \'Inter Fallback 2\', system-ui, -apple-system, \'Segoe UI\', \'Apple SD Gothic Neo\', \'Malgun Gothic\', \'Noto Sans CJK KR\', \'Noto Sans KR\', sans-serif}',
	'source-sans' => ':root{--font-reading:\'Source Sans 3\', \'Source Sans 3 Fallback\', \'Source Sans 3 Fallback 2\', system-ui, -apple-system, \'PingFang SC\', \'Microsoft YaHei\', \'Noto Sans CJK SC\', \'Noto Sans SC\', \'Hiragino Sans\', \'Yu Gothic\', \'Noto Sans CJK JP\', \'Noto Sans JP\', \'Apple SD Gothic Neo\', \'Malgun Gothic\', \'Noto Sans CJK KR\', \'Noto Sans KR\', sans-serif}:lang(zh){--font-reading:\'Source Sans 3\', \'Source Sans 3 Fallback\', \'Source Sans 3 Fallback 2\', system-ui, -apple-system, \'PingFang SC\', \'Microsoft YaHei\', \'Noto Sans CJK SC\', \'Noto Sans SC\', sans-serif}:lang(ja){--font-reading:\'Source Sans 3\', \'Source Sans 3 Fallback\', \'Source Sans 3 Fallback 2\', system-ui, -apple-system, \'Hiragino Sans\', \'Yu Gothic\', \'Noto Sans CJK JP\', \'Noto Sans JP\', sans-serif}:lang(ko){--font-reading:\'Source Sans 3\', \'Source Sans 3 Fallback\', \'Source Sans 3 Fallback 2\', system-ui, -apple-system, \'Apple SD Gothic Neo\', \'Malgun Gothic\', \'Noto Sans CJK KR\', \'Noto Sans KR\', sans-serif}',
	'literata' => ':root{--font-reading:\'Literata\', \'Literata Fallback\', \'Literata Fallback 2\', Georgia, \'Times New Roman\', \'Songti SC\', \'SimSun\', \'Noto Serif CJK SC\', \'Noto Serif SC\', \'Hiragino Mincho ProN\', \'Yu Mincho\', \'Noto Serif CJK JP\', \'Noto Serif JP\', \'Nanum Myeongjo\', \'Apple SD Gothic Neo\', \'Noto Serif CJK KR\', \'Noto Serif KR\', serif;--reading-bold:600}:lang(zh){--font-reading:\'Literata\', \'Literata Fallback\', \'Literata Fallback 2\', Georgia, \'Times New Roman\', \'Songti SC\', \'SimSun\', \'Noto Serif CJK SC\', \'Noto Serif SC\', serif}:lang(ja){--font-reading:\'Literata\', \'Literata Fallback\', \'Literata Fallback 2\', Georgia, \'Times New Roman\', \'Hiragino Mincho ProN\', \'Yu Mincho\', \'Noto Serif CJK JP\', \'Noto Serif JP\', serif}:lang(ko){--font-reading:\'Literata\', \'Literata Fallback\', \'Literata Fallback 2\', Georgia, \'Times New Roman\', \'Nanum Myeongjo\', \'Apple SD Gothic Neo\', \'Noto Serif CJK KR\', \'Noto Serif KR\', serif}',
	'source-serif' => ':root{--font-reading:\'Source Serif 4\', \'Source Serif 4 Fallback\', \'Source Serif 4 Fallback 2\', Georgia, \'Times New Roman\', \'Songti SC\', \'SimSun\', \'Noto Serif CJK SC\', \'Noto Serif SC\', \'Hiragino Mincho ProN\', \'Yu Mincho\', \'Noto Serif CJK JP\', \'Noto Serif JP\', \'Nanum Myeongjo\', \'Apple SD Gothic Neo\', \'Noto Serif CJK KR\', \'Noto Serif KR\', serif;--reading-bold:600}:lang(zh){--font-reading:\'Source Serif 4\', \'Source Serif 4 Fallback\', \'Source Serif 4 Fallback 2\', Georgia, \'Times New Roman\', \'Songti SC\', \'SimSun\', \'Noto Serif CJK SC\', \'Noto Serif SC\', serif}:lang(ja){--font-reading:\'Source Serif 4\', \'Source Serif 4 Fallback\', \'Source Serif 4 Fallback 2\', Georgia, \'Times New Roman\', \'Hiragino Mincho ProN\', \'Yu Mincho\', \'Noto Serif CJK JP\', \'Noto Serif JP\', serif}:lang(ko){--font-reading:\'Source Serif 4\', \'Source Serif 4 Fallback\', \'Source Serif 4 Fallback 2\', Georgia, \'Times New Roman\', \'Nanum Myeongjo\', \'Apple SD Gothic Neo\', \'Noto Serif CJK KR\', \'Noto Serif KR\', serif}',
	);
}

/**
 * Chrome typeface id => the family for the furniture.
 *
 * @return array<string,string>
 */
function quireink_chrome_css() {
	return array(
	'inter' => '',
	'reading' => ':root{--font-sans:var(--font-reading)}',
	'plex-mono' => ':root{--font-sans:\'IBM Plex Mono\', ui-monospace, \'SFMono-Regular\', Menlo, Consolas, monospace}',
	'jetbrains-mono' => ':root{--font-sans:\'JetBrains Mono\', ui-monospace, \'SFMono-Regular\', Menlo, Consolas, monospace}',
	);
}

/**
 * Reading face and furniture face => the woff2 files that earn a `<link rel="preload">`.
 *
 * Keyed `<reading>|<furniture>`, then by the site's language. `*` is what a language gets
 * unless it is named; a named one is an exception the blog engine's own rule makes - a second
 * subset where the faces carry the accents, nothing at all where they carry no glyph the page
 * will paint in.
 *
 * @return array<string,array<string,array<int,string>>>
 */
function quireink_font_preload() {
	return array(
	'inter|inter' => array(
		'*' => array('inter-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('inter-latin.woff2', 'inter-vietnamese.woff2'),
		'zh' => array(),
	),
	'inter|reading' => array(
		'*' => array('inter-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('inter-latin.woff2', 'inter-vietnamese.woff2'),
		'zh' => array(),
	),
	'inter|plex-mono' => array(
		'*' => array('inter-latin.woff2', 'plexmono-400-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('inter-latin.woff2', 'inter-vietnamese.woff2', 'plexmono-400-latin.woff2', 'plexmono-400-vietnamese.woff2'),
		'zh' => array(),
	),
	'inter|jetbrains-mono' => array(
		'*' => array('inter-latin.woff2', 'jetbrainsmono-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('inter-latin.woff2', 'inter-vietnamese.woff2', 'jetbrainsmono-latin.woff2', 'jetbrainsmono-vietnamese.woff2'),
		'zh' => array(),
	),
	'source-sans|inter' => array(
		'*' => array('sourcesans-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('sourcesans-latin.woff2', 'sourcesans-vietnamese.woff2'),
		'zh' => array(),
	),
	'source-sans|reading' => array(
		'*' => array('sourcesans-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('sourcesans-latin.woff2', 'sourcesans-vietnamese.woff2'),
		'zh' => array(),
	),
	'source-sans|plex-mono' => array(
		'*' => array('sourcesans-latin.woff2', 'plexmono-400-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('sourcesans-latin.woff2', 'sourcesans-vietnamese.woff2', 'plexmono-400-latin.woff2', 'plexmono-400-vietnamese.woff2'),
		'zh' => array(),
	),
	'source-sans|jetbrains-mono' => array(
		'*' => array('sourcesans-latin.woff2', 'jetbrainsmono-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('sourcesans-latin.woff2', 'sourcesans-vietnamese.woff2', 'jetbrainsmono-latin.woff2', 'jetbrainsmono-vietnamese.woff2'),
		'zh' => array(),
	),
	'literata|inter' => array(
		'*' => array('literata-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('literata-latin.woff2', 'literata-vietnamese.woff2'),
		'zh' => array(),
	),
	'literata|reading' => array(
		'*' => array('literata-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('literata-latin.woff2', 'literata-vietnamese.woff2'),
		'zh' => array(),
	),
	'literata|plex-mono' => array(
		'*' => array('literata-latin.woff2', 'plexmono-400-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('literata-latin.woff2', 'literata-vietnamese.woff2', 'plexmono-400-latin.woff2', 'plexmono-400-vietnamese.woff2'),
		'zh' => array(),
	),
	'literata|jetbrains-mono' => array(
		'*' => array('literata-latin.woff2', 'jetbrainsmono-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('literata-latin.woff2', 'literata-vietnamese.woff2', 'jetbrainsmono-latin.woff2', 'jetbrainsmono-vietnamese.woff2'),
		'zh' => array(),
	),
	'source-serif|inter' => array(
		'*' => array('sourceserif-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('sourceserif-latin.woff2', 'sourceserif-vietnamese.woff2'),
		'zh' => array(),
	),
	'source-serif|reading' => array(
		'*' => array('sourceserif-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('sourceserif-latin.woff2', 'sourceserif-vietnamese.woff2'),
		'zh' => array(),
	),
	'source-serif|plex-mono' => array(
		'*' => array('sourceserif-latin.woff2', 'plexmono-400-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('sourceserif-latin.woff2', 'sourceserif-vietnamese.woff2', 'plexmono-400-latin.woff2', 'plexmono-400-vietnamese.woff2'),
		'zh' => array(),
	),
	'source-serif|jetbrains-mono' => array(
		'*' => array('sourceserif-latin.woff2', 'jetbrainsmono-latin.woff2'),
		'ja' => array(),
		'ko' => array(),
		'ru' => array(),
		'vi' => array('sourceserif-latin.woff2', 'sourceserif-vietnamese.woff2', 'jetbrainsmono-latin.woff2', 'jetbrainsmono-vietnamese.woff2'),
		'zh' => array(),
	),
	);
}

/**
 * Frame id => the four `--fig-default-*` variables `figure img` reads when a picture names
 * no frame of its own. `none` is absent because it emits nothing.
 *
 * @return array<string,string>
 */
function quireink_figure_css() {
	return array(
	'thin' => ':root{--fig-default-pad:var(--fig-step-thin);--fig-default-mat:var(--c-bg);--fig-default-bw:1px;--fig-default-line:var(--c-rule);--fig-default-line:color-mix(in srgb,var(--c-rule),var(--c-meta) 35%)}',
	'thin-ink' => ':root{--fig-default-pad:var(--fig-step-thin);--fig-default-mat:var(--c-heading);--fig-default-bw:1px;--fig-default-line:var(--c-rule);--fig-default-line:var(--c-heading)}',
	'medium' => ':root{--fig-default-pad:var(--fig-step-med);--fig-default-mat:var(--c-bg);--fig-default-bw:1px;--fig-default-line:var(--c-rule);--fig-default-line:color-mix(in srgb,var(--c-rule),var(--c-meta) 35%)}',
	'medium-ink' => ':root{--fig-default-pad:var(--fig-step-med);--fig-default-mat:var(--c-heading);--fig-default-bw:1px;--fig-default-line:var(--c-rule);--fig-default-line:var(--c-heading)}',
	'thick' => ':root{--fig-default-pad:var(--fig-step-thick);--fig-default-mat:var(--c-bg);--fig-default-bw:1px;--fig-default-line:var(--c-rule);--fig-default-line:color-mix(in srgb,var(--c-rule),var(--c-meta) 35%)}',
	'thick-ink' => ':root{--fig-default-pad:var(--fig-step-thick);--fig-default-mat:var(--c-heading);--fig-default-bw:1px;--fig-default-line:var(--c-rule);--fig-default-line:var(--c-heading)}',
	);
}
