/**
 * Pull the look out of Quire Ink and into the theme, by RUNNING Quire Ink's own emitters.
 *
 * Nothing here retypes a colour, a size or a rule. `tools/tsconfig.json` maps `@/*` at the
 * sibling checkout, so every value below is the value the live site renders with; when the
 * blog's front end moves, this is re-run rather than re-read. The Quire Ink commit it was
 * taken from is written into the manifest, so a stale copy is a diff and not a guess.
 *
 * Emits, into theme/:
 *   assets/css/quireink-base.css   the hand-written public sheet (PUBLIC_CSS)
 *   assets/css/quireink-tokens.css palette + type scale + shape, for DEFAULT_SETTINGS
 *   assets/fonts/*.woff2           the self-hosted faces the default preset can reach
 *   theme.json                     the same palette and scale, in the block editor's dialect
 *   ../tools/extract-manifest.json what came from where, and at which commit
 */
import { mkdir, writeFile, readdir, copyFile, rm } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { $ } from 'bun'

import { PUBLIC_CSS } from '@/web/public.css'
import { DEFAULT_SETTINGS } from '@/content/settings'
import {
  themesToCss, fontPresetCss, chromeFontCss, THEME_PRESETS, TYPE_ROLES,
} from '@/content/themes'
import { cjkLangCss } from '@/content/fonts'
import { typographyToCss, shapeToCss, tableToCss } from '@/content/settings'
import { allFontFaceCss, MONO_TRACKING } from '@/render/font-faces'
import { INK_HIGHLIGHT_CSS, INK_LINES_CSS } from '@/web/ink.css'
import { singleRailCss } from '@/render/rail-css'

const HERE = dirname(import.meta.dir)
const QUIRE = join(HERE, '..', 'quireink')
const THEME = join(HERE, 'theme')

const s = DEFAULT_SETTINGS

// ---------------------------------------------------------------- the two sheets

// The order is `layout.ts`'s `pageStyles()`, which is load-bearing: --density must be
// declared before the block that multiplies it into --sp, and the palette before the type
// scale. Read the two side by side when either moves.
//
// Four entries of that list are left out, and all four for the same reason: on DEFAULT
// settings they emit the empty string. `selectionCss` and `penGesturesCss` only speak when
// an owner has changed an ink or switched a gesture off; `figureCss` says nothing when the
// site-wide frame is 'none', which is the default; `galleryCss` the same. A theme has no
// owner yet, so there is nothing for them to say — and each becomes a Customizer control
// here on the day it does.
const tokens = [
  '/* Generated by tools/extract.ts — do not edit. Run `bun tools/extract.ts`. */',
  allFontFaceCss(),
  // The three font HANDLES. Missing this block was invisible in a diff and obvious on a
  // screen: `--font-reading` is what `.prose` asks for, and with no declaration the article
  // fell back to the browser's serif while every other part of the page looked correct.
  `:root{--font-sans:'Inter', 'Inter Fallback', system-ui, -apple-system, 'Segoe UI', sans-serif;`
    + `--font-reading:var(--font-sans);`
    + `--font-mono:'JetBrains Mono', ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace}`,
  // The reading column. `.wrap` reads `--shell-w` with a 42rem fallback, so a missing
  // declaration is not a broken page — it is a page that quietly ignores the setting.
  `:root{--shell-w:${s.contentWidth}px}`,
  // The desktop rail, and the reason the table of contents did not appear at 1440px on the
  // first screenshot: below the breakpoint `.rail` is a slide-out drawer, and ONLY these
  // generated rules promote it into the gutter. They are generated rather than written
  // because a media query cannot read a CSS variable and the breakpoint is COMPUTED from
  // the column width — the rail moves out only when there is room on BOTH sides, so the
  // column stays centred.
  singleRailCss(s.contentWidth),
  fontPresetCss(s.fontPreset),
  cjkLangCss(s.fontPreset),
  chromeFontCss(s.chromeFont),
  themesToCss(s.themes, s.themePreset, undefined, s.defaultScheme),
  shapeToCss(s.shape),
  tableToCss(s.table),
  typographyToCss(s.typography),
  MONO_TRACKING,
].filter(Boolean).join('\n')
  // Quire Ink serves its faces from the site root; a WordPress theme is a folder somewhere
  // under wp-content. Relative is the answer that needs no PHP: a url() in a stylesheet
  // resolves against THAT stylesheet, and both directories are siblings under assets/.
  .replaceAll("url('/fonts/", "url('../fonts/")

await mkdir(join(THEME, 'assets', 'css'), { recursive: true })
await writeFile(join(THEME, 'assets', 'css', 'quireink-base.css'),
  '/* Copied verbatim from Quire Ink src/web/*.css.ts by tools/extract.ts. */\n' + PUBLIC_CSS + '\n')
await writeFile(join(THEME, 'assets', 'css', 'quireink-tokens.css'), tokens + '\n')

// ---------------------------------------------------------------- the pen

// The pen is NOT part of the public sheet, and finding that out cost a screenshot: every
// `<mark>` rendered as the browser's yellow rectangle because `public.css.ts` imports only
// the LINK half of ink.css. The other two halves are hashed into files of their own and
// linked per page, when the HTML actually contains the element they serve (ADR 0027) - the
// pen is heavy and most pages never uncap it.
//
// Both halves go into one file here and functions.php keeps the conditional link, which is
// the same bargain one round trip cheaper: a WordPress theme cannot hash-and-serve two
// stylesheets per request without a build step, and a post that uses one gesture almost
// always uses the other.
await writeFile(join(THEME, 'assets', 'css', 'quireink-ink.css'),
  '/* Copied from Quire Ink src/web/ink.css.ts by tools/extract.ts. */\n'
  + INK_HIGHLIGHT_CSS + '\n' + INK_LINES_CSS + '\n')

// ---------------------------------------------------------------- the faces

const FONT_SRC = join(QUIRE, 'src', 'assets', 'static', 'fonts')
const FONT_DST = join(THEME, 'assets', 'fonts')
await rm(FONT_DST, { recursive: true, force: true })
await mkdir(FONT_DST, { recursive: true })
const faces = (await readdir(FONT_SRC)).filter((f) => f.endsWith('.woff2'))
for (const f of faces) await copyFile(join(FONT_SRC, f), join(FONT_DST, f))

// ---------------------------------------------------------------- the islands

// Quire Ink's own reader bundles, built by its `build:assets`. `core` is the chrome (palette
// switch, rail, search overlay, back-to-top, newsletter) and `post` is the article (table of
// contents scrollspy, book mode, lightbox, quote copy, resume). They are copied rather than
// rewritten, which is the whole point — a second implementation of book mode would be a
// second thing to be wrong.
//
// Two of core's features talk to endpoints WordPress does not have (the newsletter form and
// the comment thread post to Quire Ink's API). They fail the way any fetch to a 404 fails,
// which is quietly; wiring them to WordPress is a decision for later and is written up in
// docs/gaps.md rather than patched in here.
const JS_SRC = join(QUIRE, 'src', 'assets', 'dist')
const JS_DST = join(THEME, 'assets', 'js')
await mkdir(JS_DST, { recursive: true })
const bundles = ['core.js', 'post.js']
for (const b of bundles) await copyFile(join(JS_SRC, b), join(JS_DST, b))

// ---------------------------------------------------------------- theme.json

// The block editor cannot read a CSS variable it was never told about, so the palette and
// the scale are declared a second time in its own dialect — pointing AT the variables rather
// than repeating their values, which is what keeps one source of truth after this file runs.
const palette = THEME_PRESETS[0]!.theme.light
const colorSlugs = Object.keys(palette)
const themeJson = {
  $schema: 'https://schemas.wp.org/trunk/theme.json',
  version: 3,
  settings: {
    appearanceTools: true,
    useRootPaddingAwareAlignments: true,
    layout: { contentSize: '38rem', wideSize: '52rem' },
    color: {
      defaultPalette: false,
      defaultGradients: false,
      custom: false,
      palette: colorSlugs.map((slug) => ({
        slug,
        name: slug.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase()),
        color: `var(--c-${slug.replace(/([A-Z])/g, '-$1').toLowerCase()})`,
      })),
    },
    typography: {
      fluid: false,
      customFontSize: false,
      fontSizes: TYPE_ROLES.map((role) => ({
        slug: role,
        name: role.toUpperCase(),
        size: `var(--fs-${role})`,
      })),
    },
    spacing: {
      units: ['rem', 'px', '%'],
      spacingSizes: [
        { slug: 'tight', name: 'Tight', size: 'calc(var(--sp) * .5)' },
        { slug: 'normal', name: 'Normal', size: 'var(--sp)' },
        { slug: 'loose', name: 'Loose', size: 'calc(var(--sp) * 2)' },
      ],
    },
  },
  styles: {
    color: { background: 'var(--c-bg)', text: 'var(--c-text)' },
    typography: {
      fontFamily: 'var(--font-reading)',
      fontSize: 'var(--fs-body)',
      lineHeight: 'var(--lh-body)',
    },
    elements: {
      link: { color: { text: 'var(--c-link)' } },
      heading: {
        color: { text: 'var(--c-heading)' },
        typography: { fontWeight: 'var(--fw-heading)' },
      },
    },
  },
  templateParts: [
    { name: 'header', title: 'Header', area: 'header' },
    { name: 'footer', title: 'Footer', area: 'footer' },
  ],
}
await writeFile(join(THEME, 'theme.json'), JSON.stringify(themeJson, null, 2) + '\n')

// ---------------------------------------------------------------- the receipt

const sha = (await $`git -C ${QUIRE} rev-parse HEAD`.text()).trim()
const dirty = (await $`git -C ${QUIRE} status --porcelain`.text()).trim() !== ''
await writeFile(join(HERE, 'tools', 'extract-manifest.json'), JSON.stringify({
  takenFrom: { repo: 'quireink', commit: sha, workingTreeDirty: dirty },
  emitted: {
    'theme/assets/css/quireink-base.css': PUBLIC_CSS.length,
    'theme/assets/css/quireink-tokens.css': tokens.length,
    'theme/assets/css/quireink-ink.css': INK_HIGHLIGHT_CSS.length + INK_LINES_CSS.length,
    'theme/assets/fonts': faces.length,
    'theme/assets/js': bundles,
  },
  palettes: THEME_PRESETS.map((p) => p.id),
  typeRoles: TYPE_ROLES,
  fontPreset: s.fontPreset,
  chromeFont: s.chromeFont,
}, null, 2) + '\n')

console.log(`base   ${PUBLIC_CSS.length} B`)
console.log(`tokens ${tokens.length} B`)
console.log(`ink    ${INK_HIGHLIGHT_CSS.length + INK_LINES_CSS.length} B`)
console.log(`fonts  ${faces.length} files`)
console.log(`js     ${bundles.join(', ')}`)
console.log(`from   quireink@${sha.slice(0, 7)}${dirty ? ' (dirty)' : ''}`)
