/**
 * Pull the look out of Quire Ink and into the theme, by RUNNING Quire Ink's own emitters.
 *
 * Nothing here retypes a colour, a size or a rule. `tools/tsconfig.json` maps `@/*` at the
 * sibling checkout, so every value below is the value the live site renders with; when the
 * blog's front end moves, this is re-run rather than re-read. The Quire Ink commit it was
 * taken from is written into the manifest, so a stale copy is a diff and not a guess.
 *
 * Emits, into theme/:
 *   assets/css/quireink-base.css   the hand-written public sheet (PUBLIC_CSS)
 *   assets/css/quireink-tokens.css palette + type scale + shape, for DEFAULT_SETTINGS
 *   assets/fonts/*.woff2           the self-hosted faces the default preset can reach
 *   theme.json                     the same palette and scale, in the block editor's dialect
 *   ../tools/extract-manifest.json what came from where, and at which commit
 */
import { mkdir, writeFile, readdir, copyFile, rm } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { $ } from 'bun'

import { PUBLIC_CSS } from '@/web/public.css'
import { DEFAULT_SETTINGS } from '@/content/settings'
import {
  themesToCss, fontPresetCss, chromeFontCss, THEME_PRESETS, TYPE_ROLES,
} from '@/content/themes'
import { cjkLangCss } from '@/content/fonts'
import { typographyToCss, shapeToCss, tableToCss } from '@/content/settings'
import { allFontFaceCss, MONO_TRACKING } from '@/render/font-faces'
import { singleRailCss, timelineCss } from '@/render/rail-css'
import { FONT_PRESETS, CHROME_FONTS, SCHEMES } from '@/content/themes'

const HERE = dirname(import.meta.dir)
const QUIRE = join(HERE, '..', 'quireink')
// Normally the theme itself. `EXTRACT_OUT` points it elsewhere so
// `tools/checks/generated-in-sync.ts` can produce a fresh copy and compare bytes without
// touching what is committed — a check that has to modify the tree to run is a check people
// turn off.
const THEME = process.env.EXTRACT_OUT ?? join(HERE, 'quire-ink')

const s = DEFAULT_SETTINGS

// ---------------------------------------------------------------- the two sheets

// The order is `layout.ts`'s `pageStyles()`, which is load-bearing: --density must be
// declared before the block that multiplies it into --sp, and the palette before the type
// scale. Read the two side by side when either moves.
//
// Four entries of that list are left out, and all four for the same reason: on DEFAULT
// settings they emit the empty string. `selectionCss` and `penGesturesCss` only speak when
// an owner has changed an ink or switched a gesture off; `figureCss` says nothing when the
// site-wide frame is 'none', which is the default; `galleryCss` the same. A theme has no
// owner yet, so there is nothing for them to say — and each becomes a Customizer control
// here on the day it does.
const tokens = [
  '/* Generated by tools/extract.ts — do not edit. Run `bun tools/extract.ts`. */',
  allFontFaceCss(),
  // The three font HANDLES. Missing this block was invisible in a diff and obvious on a
  // screen: `--font-reading` is what `.prose` asks for, and with no declaration the article
  // fell back to the browser's serif while every other part of the page looked correct.
  `:root{--font-sans:'Inter', 'Inter Fallback', system-ui, -apple-system, 'Segoe UI', sans-serif;`
    + `--font-reading:var(--font-sans);`
    + `--font-mono:'JetBrains Mono', ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace}`,
  // The reading column. `.wrap` reads `--shell-w` with a 42rem fallback, so a missing
  // declaration is not a broken page — it is a page that quietly ignores the setting.
  `:root{--shell-w:${s.contentWidth}px}`,
  // The desktop rail, and the reason the table of contents did not appear at 1440px on the
  // first screenshot: below the breakpoint `.rail` is a slide-out drawer, and ONLY these
  // generated rules promote it into the gutter. They are generated rather than written
  // because a media query cannot read a CSS variable and the breakpoint is COMPUTED from
  // the column width — the rail moves out only when there is room on BOTH sides, so the
  // column stays centred.
  singleRailCss(s.contentWidth),
  // The listing's gutter timeline: the spine, the sticky year tag and the month markers.
  // In the blog engine this arrives through `pageStyles(settings, extra)` because it is
  // page-specific; a theme has one stylesheet for every page, so it is emitted here and is
  // inert on a page with no `.tl-*` in it.
  //
  // It has to be emitted at all, and that is not obvious: the base sheet styles what a year
  // tag LOOKS like, and only this function positions it. Without it the markers do not sit
  // in the gutter — they sit in the text, in reading order, and the feed reads as if
  // somebody typed the month into the middle of the page. Its first line is
  // `.tl-mark,.tl-year{display:none}`, so the fallback is invisible rather than wrong.
  //
  // Its breakpoint is LOWER than the rail's, deliberately: a month label needs ~130px of
  // gutter and a sidebar needs 250px, so the timeline shows on a laptop where the sidebar
  // has already folded away.
  timelineCss(s.contentWidth),
  fontPresetCss(s.fontPreset),
  cjkLangCss(s.fontPreset),
  chromeFontCss(s.chromeFont),
  themesToCss(s.themes, s.themePreset, undefined, s.defaultScheme),
  shapeToCss(s.shape),
  tableToCss(s.table),
  typographyToCss(s.typography),
  MONO_TRACKING,
].filter(Boolean).join('\n')
  // Quire Ink serves its faces from the site root; a WordPress theme is a folder somewhere
  // under wp-content. Relative is the answer that needs no PHP: a url() in a stylesheet
  // resolves against THAT stylesheet, and both directories are siblings under assets/.
  .replaceAll("url('/fonts/", "url('../fonts/")

await mkdir(join(THEME, 'assets', 'css'), { recursive: true })
await writeFile(join(THEME, 'assets', 'css', 'quireink-base.css'),
  '/* Copied verbatim from Quire Ink src/web/*.css.ts by tools/extract.ts. */\n' + PUBLIC_CSS + '\n')
await writeFile(join(THEME, 'assets', 'css', 'quireink-tokens.css'), tokens + '\n')

// ---------------------------------------------------------------- the pen, deliberately absent
//
// Quire Ink's pen sheet is NOT emitted here, and that is a decision rather than an omission
// (docs/decisions/0003-skip-what-gutenberg-cannot-express.md).
//
// The strokes are 273 KB of generated SVG keyed on `data-pen="0..N"` and `data-form=o`,
// attributes only Quire Ink's editor produces. The block editor has no way to write one, so
// on a WordPress site the sheet is 273 KB that can never match a single element. It was
// shipped for one afternoon, conditionally linked, before anyone asked who would author the
// markup it styles.
//
// Imported content still carries the attributes; `dev/seed/fetch.py` strips them on the way
// in for the same reason.

// ---------------------------------------------------------------- the faces

const FONT_SRC = join(QUIRE, 'src', 'assets', 'static', 'fonts')
const FONT_DST = join(THEME, 'assets', 'fonts')
await rm(FONT_DST, { recursive: true, force: true })
await mkdir(FONT_DST, { recursive: true })
const faces = (await readdir(FONT_SRC)).filter((f) => f.endsWith('.woff2'))
for (const f of faces) await copyFile(join(FONT_SRC, f), join(FONT_DST, f))

// ---------------------------------------------------------------- the islands

// Quire Ink's own reader bundles, built by its `build:assets`. `core` is the chrome (palette
// switch, rail, search overlay, back-to-top, newsletter) and `post` is the article (table of
// contents scrollspy, book mode, lightbox, quote copy, resume). They are copied rather than
// rewritten, which is the whole point — a second implementation of book mode would be a
// second thing to be wrong.
//
// Two of core's features talk to endpoints WordPress does not have (the newsletter form and
// the comment thread post to Quire Ink's API). They fail the way any fetch to a 404 fails,
// which is quietly; wiring them to WordPress is a decision for later and is written up in
// docs/gaps.md rather than patched in here.
const JS_SRC = join(QUIRE, 'src', 'assets', 'dist')
const JS_DST = join(THEME, 'assets', 'js')
await mkdir(JS_DST, { recursive: true })
const bundles = ['core.js', 'post.js']
for (const b of bundles) await copyFile(join(JS_SRC, b), join(JS_DST, b))

// ---------------------------------------------------------------- the owner's choices, as PHP

// The palette and the typeface are SETTINGS in the blog engine and were baked constants here
// until an owner asked where to change them. They cannot live in the static sheet: which of
// the six is the default, and which typeface the words are set in, are decisions a site makes
// after it installs the theme.
//
// So the emitters are run once per possible answer and the results written out as a PHP map,
// which `quireink_appearance_css()` picks from at request time. It is generated, so the
// no-hand-copying rule still holds: every string below is what the blog engine produces for
// that combination, not a value anybody read off a screen.
//
// The whole file is ~14 KB of PHP that is never sent to a browser; what reaches the page is
// one block of a few hundred bytes, and nothing at all when the owner has changed nothing.
const phpString = (v: string) => `'${v.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`

const paletteEntries = THEME_PRESETS.map((preset) => {
  const perScheme = SCHEMES.map((scheme) => {
    // `enabled: []` keeps this to the :root/.dark pair plus the first-paint rule for that
    // scheme — the `[data-palette]` blocks the switcher needs are already in the static
    // sheet and repeating them per palette would be six copies of the same six rules.
    const css = themesToCss({ [preset.id]: preset.theme }, preset.id, [], scheme)
    return `\t\t'${scheme}' => ${phpString(css)},`
  }).join('\n')
  return `\t'${preset.id}' => array(\n${perScheme}\n\t),`
}).join('\n')

const fontEntries = FONT_PRESETS.map((f) =>
  `\t'${f.id}' => ${phpString(fontPresetCss(f.id) + cjkLangCss(f.id))},`).join('\n')

const chromeEntries = CHROME_FONTS.map((c) =>
  `\t'${c.id}' => ${phpString(chromeFontCss(c.id))},`).join('\n')

const generatedPhp = `<?php
/**
 * GENERATED by tools/extract.ts — do not edit. Run \`bun tools/extract.ts\`.
 *
 * Every palette and every typeface the blog engine offers, already turned into CSS by the
 * blog engine's own emitters. \`quireink_appearance_css()\` in inc/customizer.php picks the
 * one the owner chose and prints it after the stylesheets, exactly where Quire Ink inlines
 * its own settings block.
 *
 * @package QuireInk
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Palette id => first-paint scheme => the :root and .dark declarations.
 *
 * @return array<string,array<string,string>>
 */
function quireink_palette_css() {
	return array(
${paletteEntries}
	);
}

/**
 * Reading typeface id => the family, the type scale tuned for it, and its CJK tail.
 *
 * @return array<string,string>
 */
function quireink_font_css() {
	return array(
${fontEntries}
	);
}

/**
 * Chrome typeface id => the family for the furniture.
 *
 * @return array<string,string>
 */
function quireink_chrome_css() {
	return array(
${chromeEntries}
	);
}
`

if (!process.env.EXTRACT_OUT) {
  await writeFile(join(HERE, 'quire-ink', 'inc', 'generated-appearance.php'), generatedPhp)
}

// ---------------------------------------------------------------- theme.json

// The block editor cannot read a CSS variable it was never told about, so the palette and
// the scale are declared a second time in its own dialect — pointing AT the variables rather
// than repeating their values, which is what keeps one source of truth after this file runs.
const palette = THEME_PRESETS[0]!.theme.light
const colorSlugs = Object.keys(palette)
const themeJson = {
  $schema: 'https://schemas.wp.org/trunk/theme.json',
  version: 3,
  settings: {
    appearanceTools: true,
    useRootPaddingAwareAlignments: true,
    layout: { contentSize: '38rem', wideSize: '52rem' },
    color: {
      defaultPalette: false,
      defaultGradients: false,
      custom: false,
      palette: colorSlugs.map((slug) => ({
        slug,
        name: slug.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase()),
        color: `var(--c-${slug.replace(/([A-Z])/g, '-$1').toLowerCase()})`,
      })),
    },
    typography: {
      fluid: false,
      customFontSize: false,
      fontSizes: TYPE_ROLES.map((role) => ({
        slug: role,
        name: role.toUpperCase(),
        size: `var(--fs-${role})`,
      })),
    },
    spacing: {
      units: ['rem', 'px', '%'],
      spacingSizes: [
        { slug: 'tight', name: 'Tight', size: 'calc(var(--sp) * .5)' },
        { slug: 'normal', name: 'Normal', size: 'var(--sp)' },
        { slug: 'loose', name: 'Loose', size: 'calc(var(--sp) * 2)' },
      ],
    },
  },
  styles: {
    color: { background: 'var(--c-bg)', text: 'var(--c-text)' },
    typography: {
      fontFamily: 'var(--font-reading)',
      fontSize: 'var(--fs-body)',
      lineHeight: 'var(--lh-body)',
    },
    elements: {
      link: { color: { text: 'var(--c-link)' } },
      heading: {
        color: { text: 'var(--c-heading)' },
        typography: { fontWeight: 'var(--fw-heading)' },
      },
    },
  },
  templateParts: [
    { name: 'header', title: 'Header', area: 'header' },
    { name: 'footer', title: 'Footer', area: 'footer' },
  ],
}
if (!process.env.EXTRACT_OUT) await writeFile(join(HERE, 'quire-ink', 'theme.json'), JSON.stringify(themeJson, null, 2) + '\n')

// ---------------------------------------------------------------- the receipt

const sha = (await $`git -C ${QUIRE} rev-parse HEAD`.text()).trim()
const dirty = (await $`git -C ${QUIRE} status --porcelain`.text()).trim() !== ''
if (!process.env.EXTRACT_OUT) await writeFile(join(HERE, 'tools', 'extract-manifest.json'), JSON.stringify({
  takenFrom: { repo: 'quireink', commit: sha, workingTreeDirty: dirty },
  emitted: {
    'quire-ink/assets/css/quireink-base.css': PUBLIC_CSS.length,
    'quire-ink/assets/css/quireink-tokens.css': tokens.length,
    'quire-ink/assets/fonts': faces.length,
    'quire-ink/assets/js': bundles,
  },
  palettes: THEME_PRESETS.map((p) => p.id),
  typeRoles: TYPE_ROLES,
  fontPreset: s.fontPreset,
  chromeFont: s.chromeFont,
}, null, 2) + '\n')

console.log(`base   ${PUBLIC_CSS.length} B`)
console.log(`tokens ${tokens.length} B`)
console.log(`fonts  ${faces.length} files`)
console.log(`js     ${bundles.join(', ')}`)
console.log(`php    ${THEME_PRESETS.length} palettes x ${SCHEMES.length} schemes, ${FONT_PRESETS.length} fonts, ${CHROME_FONTS.length} chrome (${generatedPhp.length} B)`)
console.log(`from   quireink@${sha.slice(0, 7)}${dirty ? ' (dirty)' : ''}`)
