/**
 * Pull the look out of Quire Ink and into the theme, by RUNNING Quire Ink's own emitters.
 *
 * Nothing here retypes a colour, a size or a rule. `tools/tsconfig.json` maps `@/*` at the
 * sibling checkout, so every value below is the value the live site renders with; when the
 * blog's front end moves, this is re-run rather than re-read. The Quire Ink commit it was
 * taken from is written into the manifest, so a stale copy is a diff and not a guess.
 *
 * Emits, into theme/:
 *   assets/css/quireink-base.css   the hand-written public sheet (PUBLIC_CSS)
 *   assets/css/quireink-look-code.css  the source-code look, left unloaded when it is off
 *   rtl.css                        the mirrored diff of all four sheets, for an RTL locale
 *   assets/css/editor.css          the article's own rules, addressed at the editor canvas
 *   assets/css/quireink-tokens.css palette + type scale + shape, for DEFAULT_SETTINGS
 *   assets/fonts/*.woff2           the self-hosted faces the default preset can reach
 *   theme.json                     the same palette and scale, in the block editor's dialect
 *   ../tools/extract-manifest.json what came from where, and at which commit
 */
import { mkdir, writeFile, readdir, copyFile, rm } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { $ } from 'bun'

import { PUBLIC_CSS } from '@/web/public.css'
import { LOOK_CODE_CSS } from '@/web/look-code.css'
import { minifyCss } from '@/web/css-min'

import { flipCss } from './rtl'
import { DEFAULT_SETTINGS } from '@/content/settings'
import {
  themesToCss, fontPresetCss, chromeFontCss, THEME_PRESETS, TYPE_ROLES,
} from '@/content/themes'
import { cjkLangCss } from '@/content/fonts'
import { typographyToCss, shapeToCss, tableToCss } from '@/content/settings'
import { allFontFaceCss, monoTracking } from '@/render/font-faces'
import { singleRailCss, timelineCss, RAIL_W, RAIL_GAP } from '@/render/rail-css'

import { APPEARANCE_PHP, APPEARANCE_COUNTS } from './appearance-php'
import { editorCss } from './editor-css'
import { copyAssets } from './extract-assets'
import { FONT_PRESETS, CHROME_FONTS, SCHEMES } from '@/content/themes'

const HERE = dirname(import.meta.dir)
const QUIRE = join(HERE, '..', 'quireink')
// Normally the theme itself. `EXTRACT_OUT` points it elsewhere so
// `tools/checks/generated-in-sync.ts` can produce a fresh copy and compare bytes without
// touching what is committed — a check that has to modify the tree to run is a check people
// turn off.
const THEME = process.env.EXTRACT_OUT ?? join(HERE, 'quire-ink')

const s = DEFAULT_SETTINGS

// ---------------------------------------------------------------- the two sheets

// The order is `layout.ts`'s `pageStyles()`, which is load-bearing: --density must be
// declared before the block that multiplies it into --sp, and the palette before the type
// scale. Read the two side by side when either moves.
//
// Four entries of that list are left out, and all four for the same reason: on DEFAULT
// settings they emit the empty string. `selectionCss` and `penGesturesCss` only speak when
// an owner has changed an ink or switched a gesture off; `figureCss` says nothing when the
// site-wide frame is 'none', which is the default; `galleryCss` the same. A theme has no
// owner yet, so there is nothing for them to say — and each becomes a Customizer control
// here on the day it does.
/**
 * A face's address, moved from the site root to beside the stylesheet asking for it.
 *
 * ⚠️ IT MATCHES THE UNQUOTED SPELLING TOO, and that is not tidiness. This was a string swap
 * on `url('/fonts/` and it ran on the tokens sheet alone, because until 2026-09-16 the tokens
 * sheet held every `@font-face` in the theme. Quire Ink 2.2.10 put one in the BASE sheet, the
 * pen's numerals, and wrote it `url(/fonts/...)` with no quotes: it went through untouched and
 * a WordPress install would have asked its own site root for a file that is not there.
 */
const FONT_URL = /url\((['"]?)\/fonts\//g

const tokens = [
  '/* Generated by tools/extract.ts — do not edit. Run `bun tools/extract.ts`. */',
  allFontFaceCss(),
  // The three font HANDLES. Missing this block was invisible in a diff and obvious on a
  // screen: `--font-reading` is what `.prose` asks for, and with no declaration the article
  // fell back to the browser's serif while every other part of the page looked correct.
  `:root{--font-sans:'Inter', 'Inter Fallback', system-ui, -apple-system, 'Segoe UI', sans-serif;`
    + `--font-reading:var(--font-sans);`
    + `--font-mono:'JetBrains Mono', ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace}`,
  // The reading column. `.wrap` reads `--shell-w` with a 42rem fallback, so a missing
  // declaration is not a broken page — it is a page that quietly ignores the setting.
  `:root{--shell-w:${s.contentWidth}px}`,
  // The desktop rail, and the reason the table of contents did not appear at 1440px on the
  // first screenshot: below the breakpoint `.rail` is a slide-out drawer, and ONLY these
  // generated rules promote it into the gutter. They are generated rather than written
  // because a media query cannot read a CSS variable and the breakpoint is COMPUTED from
  // the column width — the rail moves out only when there is room on BOTH sides, so the
  // column stays centred.
  singleRailCss(s.contentWidth),
  // The listing's gutter timeline: the spine, the sticky year tag and the month markers.
  // In the blog engine this arrives through `pageStyles(settings, extra)` because it is
  // page-specific; a theme has one stylesheet for every page, so it is emitted here and is
  // inert on a page with no `.tl-*` in it.
  //
  // It has to be emitted at all, and that is not obvious: the base sheet styles what a year
  // tag LOOKS like, and only this function positions it. Without it the markers do not sit
  // in the gutter — they sit in the text, in reading order, and the feed reads as if
  // somebody typed the month into the middle of the page. Its first line is
  // `.tl-mark,.tl-year{display:none}`, so the fallback is invisible rather than wrong.
  //
  // Its breakpoint is LOWER than the rail's, deliberately: a month label needs ~130px of
  // gutter and a sidebar needs 250px, so the timeline shows on a laptop where the sidebar
  // has already folded away.
  timelineCss(s.contentWidth),
  fontPresetCss(s.fontPreset),
  cjkLangCss(s.fontPreset),
  chromeFontCss(s.chromeFont),
  themesToCss(s.themes, s.themePreset, undefined, s.defaultScheme),
  shapeToCss(s.shape),
  tableToCss(s.table),
  typographyToCss(s.typography),
  // ⚠️ ALL THREE BRANCHES, because this sheet is STATIC. Quire Ink calls `monoTracking`
  // once per page view with that page's own two settings and emits the single block it can
  // match; a theme ships one file to every reader and the switch is theirs, so all three
  // have to be in it. Built by calling the engine's own function three times rather than by
  // re-typing what it returns.
  [monoTracking('plex-mono', 'plain'), monoTracking('jetbrains-mono', 'plain'),
    monoTracking('inter', 'code')].join(''),
].filter(Boolean).join('\n')
  // Quire Ink serves its faces from the site root; a WordPress theme is a folder somewhere
  // under wp-content. Relative is the answer that needs no PHP: a url() in a stylesheet
  // resolves against THAT stylesheet, and both directories are siblings under assets/.
  .replace(FONT_URL, "url($1../fonts/")

// The source-code LOOK is a sheet of its own in the blog engine, and this theme carries that
// one of its four. It used to be a contiguous slice of `PUBLIC_CSS` that this file cut out;
// Quire Ink 2.2.10 moved every look into its own file, so there is nothing to cut any more
// and the assertion below is the inverse of the one that used to stand here: if a look ever
// goes back inside the public sheet, the theme would ship it twice and this says so.
//
// Switching it off should stop it being DOWNLOADED, not just stop it applying, which is why
// it is a second file rather than rules inside the first. The block editor never loads it:
// not one rule in it touches `.prose`, so in the editor it is bytes that cannot match.
//
// It is LIFTED, never re-typed. Order does not matter for where it is loaded, and that is a
// property rather than a hope: every selector in it carries `html[data-look=code]`, so it
// cannot tie with anything else in the theme and cannot lose a tie it never has.
if (PUBLIC_CSS.includes(LOOK_CODE_CSS.slice(0, 400))) {
  throw new Error(
    'The source-code look is inside PUBLIC_CSS again.\n'
    + '  Quire Ink has changed how src/web/public.css.ts composes the sheet.\n'
    + '  Read that file: shipping both would send the look twice.',
  )
}

/*
 * MINIFIED, because that is what the blog SERVES: `PUBLIC_CSS` is the source and
 * `minifyCss(PUBLIC_CSS)` is the file a reader downloads (`src/web/assets.ts`). Shipping the
 * source cost 198,273 B against 68,942, and 59.8 KB gzipped against 15.0 - 280 comment blocks
 * nobody on a WordPress site will ever read. docs/conventions/extract.md has the measurement.
 * The derivations below still read the unminified strings, and minify their own output.
 */
const shipCss = (css: string) => minifyCss(css.replace(FONT_URL, "url($1../fonts/"))

await mkdir(join(THEME, 'assets', 'css'), { recursive: true })
await writeFile(join(THEME, 'assets', 'css', 'quireink-base.css'),
  '/* Quire Ink src/web/*.css.ts, minified as that server serves it, by tools/extract.ts. */\n'
  + shipCss(PUBLIC_CSS) + '\n')
await writeFile(join(THEME, 'assets', 'css', 'quireink-look-code.css'),
  '/* Quire Ink src/web/look-code.css.ts, minified as that server serves it. Loaded only\n'
  + '   when the Customizer switch is on. */\n'
  + shipCss(LOOK_CODE_CSS) + '\n')
await writeFile(join(THEME, 'assets', 'css', 'quireink-tokens.css'), minifyCss(tokens) + '\n')

// ---------------------------------------------------------------- the mirror
//
// `rtl.css` in the theme ROOT is a WordPress convention with no PHP behind it: core hooks
// `locale_stylesheet()` onto `wp_head`, and for a locale whose text direction is rtl it links
// whatever `rtl.css` it finds. `wp_print_styles` runs at priority 8 and that at 10, so it
// lands after every sheet the theme enqueued, which is what makes a diff enough.
//
// It mirrors bridge.css too, which is the one sheet in here nobody generated. That is fine
// and it is the point: the mirror is derived from whatever the theme actually ships, so a
// hand-written rule that forgets RTL is answered without anyone remembering to answer it.
const bridge = await Bun.file(join(HERE, 'quire-ink', 'assets', 'css', 'bridge.css')).text()
const mirror = flipCss([
  PUBLIC_CSS,
  LOOK_CODE_CSS,
  tokens,
  bridge,
].join('\n'))
await writeFile(join(THEME, 'rtl.css'),
  '/* Generated by tools/rtl.ts from the four sheets this theme ships. Do not edit.\n'
  + '   Only what mirrors is here; everything else is already correct in both directions. */\n'
  + minifyCss(mirror.sheet))

// ---------------------------------------------------------------- the editor canvas
//
// The article's typography, again, aimed at `.editor-styles-wrapper` instead of at `.prose`.
// Built from the sheets this theme actually ships, including bridge.css, so a rule added there
// for a Gutenberg block reaches the editor without anybody remembering to copy it.
const editor = editorCss([PUBLIC_CSS, LOOK_CODE_CSS, bridge].join('\n'))
await writeFile(join(THEME, 'assets', 'css', 'editor.css'),
  '/* Generated by tools/editor-css.ts. Do not edit.\n'
  + '   Every rule scoped to .prose, re-addressed at the block editor canvas. */\n'
  + minifyCss(editor.sheet))

// ---------------------------------------------------------------- the pen, deliberately absent
//
// Quire Ink's pen sheet is NOT emitted here, and that is a decision rather than an omission
// (docs/decisions/0003-skip-what-gutenberg-cannot-express.md).
//
// The strokes are 273 KB of generated SVG keyed on `data-pen="0..N"` and `data-form=o`,
// attributes only Quire Ink's editor produces. The block editor has no way to write one, so
// on a WordPress site the sheet is 273 KB that can never match a single element. It was
// shipped for one afternoon, conditionally linked, before anyone asked who would author the
// markup it styles.
//
// Imported content still carries the attributes; `dev/seed/fetch.py` strips them on the way
// in for the same reason.

// ---------------------------------------------------------------- the faces and the islands
//
// Split into `tools/extract-assets.ts` when this file passed the 400-line ceiling, on the one
// seam it has: everything else here DERIVES a file - runs an emitter, mirrors a sheet, builds
// a table - and that half only moves bytes across from the sibling checkout.
const { faces, bundles } = await copyAssets(QUIRE, THEME, !process.env.EXTRACT_OUT)


// ---------------------------------------------------------------- the owner's choices, as PHP
//
// Built in `tools/appearance-php.ts`, which runs the blog engine's emitters once per answer an
// owner could give. ~15 KB of PHP that never reaches a browser; what reaches the page is a few
// hundred bytes, and nothing at all when the owner has changed nothing.
if (!process.env.EXTRACT_OUT) {
  await writeFile(join(HERE, 'quire-ink', 'inc', 'generated-appearance.php'), APPEARANCE_PHP)
}

// ---------------------------------------------------------------- theme.json

// The block editor cannot read a CSS variable it was never told about, so the palette and
// the scale are declared a second time in its own dialect — pointing AT the variables rather
// than repeating their values, which is what keeps one source of truth after this file runs.
const palette = THEME_PRESETS[0]!.theme.light
const colorSlugs = Object.keys(palette)
const themeJson = {
  $schema: 'https://schemas.wp.org/trunk/theme.json',
  version: 3,
  settings: {
    appearanceTools: true,
    useRootPaddingAwareAlignments: true,
    // FROM THE ENGINE'S OWN NUMBERS, not from a pair of round rem values that happened to
    // look right. They were 38rem and 52rem — 608px and 832px — against a reading column of
    // 672px and a wide figure of 962px, so the editor drew every block 64px narrower than the
    // page would and "wide" meant two different widths on the two sides of Publish.
    layout: {
      contentSize: `${s.contentWidth}px`,
      wideSize: `${s.contentWidth + RAIL_W + RAIL_GAP}px`,
    },
    color: {
      defaultPalette: false,
      defaultGradients: false,
      custom: false,
      palette: colorSlugs.map((slug) => ({
        slug,
        name: slug.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase()),
        color: `var(--c-${slug.replace(/([A-Z])/g, '-$1').toLowerCase()})`,
      })),
    },
    typography: {
      fluid: false,
      customFontSize: false,
      fontSizes: TYPE_ROLES.map((role) => ({
        slug: role,
        name: role.toUpperCase(),
        size: `var(--fs-${role})`,
      })),
    },
    spacing: {
      units: ['rem', 'px', '%'],
      spacingSizes: [
        { slug: 'tight', name: 'Tight', size: 'calc(var(--sp) * .5)' },
        { slug: 'normal', name: 'Normal', size: 'var(--sp)' },
        { slug: 'loose', name: 'Loose', size: 'calc(var(--sp) * 2)' },
      ],
    },
  },
  styles: {
    color: { background: 'var(--c-bg)', text: 'var(--c-text)' },
    typography: {
      fontFamily: 'var(--font-reading)',
      fontSize: 'var(--fs-body)',
      lineHeight: 'var(--lh-body)',
    },
    elements: {
      link: { color: { text: 'var(--c-link)' } },
      heading: {
        color: { text: 'var(--c-heading)' },
        typography: { fontWeight: 'var(--fw-heading)' },
      },
      // Every OTHER button a block can put on the page, in the language the theme's own
      // buttons already speak: a hairline, the page's ground, the heading's ink.
      //
      // Not the Button block, which `bridge.css` fills with the accent on purpose and which
      // outranks this - a call to action is meant to be loud. This is for the quiet ones,
      // and the search block is the one that proved it was needed: its button was #32373c,
      // core's default, a colour that appears in none of the six palettes.
      //
      // Every value is a token this theme already publishes, so a palette change moves them
      // with everything else.
      button: {
        color: { background: 'var(--c-bg)', text: 'var(--c-heading)' },
        border: {
          color: 'var(--c-rule)',
          width: '1px',
          style: 'solid',
          radius: 'var(--radius, .5rem)',
        },
        typography: { fontWeight: '500' },
        ':hover': { color: { background: 'var(--c-rule)', text: 'var(--c-heading)' } },
        ':focus': { color: { background: 'var(--c-rule)', text: 'var(--c-heading)' } },
      },
    },
  },
  templateParts: [
    { name: 'header', title: 'Header', area: 'header' },
    { name: 'footer', title: 'Footer', area: 'footer' },
  ],
}
if (!process.env.EXTRACT_OUT) await writeFile(join(HERE, 'quire-ink', 'theme.json'), JSON.stringify(themeJson, null, 2) + '\n')

// ---------------------------------------------------------------- the faces resolve
//
// Every sheet this file writes, read back for an address that still points at a site root.
// A WordPress theme is a folder under wp-content and the blog engine serves its faces from
// `/`, so a survivor is a 404 in every install and a silent fallback to whatever the system
// has. It shipped once, on `url(/fonts/kalam-digits.woff2)`: the rewrite was a string swap on
// the QUOTED spelling and that one was written without quotes.
for (const name of ['quireink-base.css', 'quireink-look-code.css', 'quireink-tokens.css', 'editor.css']) {
  const sheet = await Bun.file(join(THEME, 'assets', 'css', name)).text()
  const stray = sheet.match(/url\((['"]?)\/fonts\/[^)]*\)/g)
  if (stray) {
    throw new Error(
      `${name} asks the site root for a face: ${stray.slice(0, 3).join(', ')}\n`
      + '  A theme is a folder under wp-content; that URL is a 404 in every install.\n'
      + '  Widen FONT_URL rather than editing the generated sheet.',
    )
  }
}

// ---------------------------------------------------------------- the receipt

const sha = (await $`git -C ${QUIRE} rev-parse HEAD`.text()).trim()
const dirty = (await $`git -C ${QUIRE} status --porcelain`.text()).trim() !== ''
if (!process.env.EXTRACT_OUT) await writeFile(join(HERE, 'tools', 'extract-manifest.json'), JSON.stringify({
  takenFrom: { repo: 'quireink', commit: sha, workingTreeDirty: dirty },
  emitted: {
    'quire-ink/assets/css/quireink-base.css': PUBLIC_CSS.length,
    'quire-ink/assets/css/quireink-look-code.css': LOOK_CODE_CSS.length,
    'quire-ink/assets/css/quireink-tokens.css': tokens.length,
    'quire-ink/rtl.css': mirror.sheet.length,
    'quire-ink/assets/fonts': faces.length,
    'quire-ink/assets/js': bundles,
  },
  palettes: THEME_PRESETS.map((p) => p.id),
  typeRoles: TYPE_ROLES,
  fontPreset: s.fontPreset,
  chromeFont: s.chromeFont,
}, null, 2) + '\n')

console.log(`base   ${PUBLIC_CSS.length} B`)
console.log(`look   ${LOOK_CODE_CSS.length} B (source code, its own sheet since 2.2.10)`)
console.log(`tokens ${tokens.length} B`)
console.log(`rtl    ${mirror.sheet.length} B, ${(mirror.sheet.match(/\{/g) ?? []).length} rules`)
console.log(`editor ${editor.sheet.length} B, ${editor.rules} rules`)
for (const w of mirror.warnings) console.log(`  ! rtl: ${w}`)
console.log(`fonts  ${faces.length} files`)
console.log(`js     ${bundles.join(', ')}`)
const c = APPEARANCE_COUNTS
console.log(`php    ${c.palettes} palettes x ${c.schemes} schemes, ${c.fonts} fonts, `
  + `${c.chrome} chrome, ${c.frames} frames (${APPEARANCE_PHP.length} B)`)
console.log(`from   quireink@${sha.slice(0, 7)}${dirty ? ' (dirty)' : ''}`)
